version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '15:37'
      timezone: 'Europe/Berlin'
    groups:
      yarn-patch:
        update-types: ['patch']
      yarn-minor:
        update-types: ['minor']
      yarn-major:
        update-types: ['major']
  - package-ecosystem: 'docker'
    directory: '/'
    groups:
      docker-all:
        patterns:
          - '*'
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: '/'
    groups:
      compose-all:
        patterns:
          - '*'
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: '/'
    groups:
      actions-all:
        patterns:
          - '*'
    schedule:
      interval: weekly
