version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '15:37'
      timezone: 'Europe/Berlin'
    groups:
      patch:
        update-types: ['patch']
      minor:
        update-types: ['minor']
      major:
        update-types: ['major']
  - package-ecosystem: 'docker'
    directory: '/'
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: '/'
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: '/'
    groups:
      all:
        patterns:
          - '*'
    schedule:
      interval: weekly
