export enum ProductLifecycleStage {
    A1ToA3 = 'A1-A3',
    A1RawMaterialSupply = 'A1',
    A2CradleToGate = 'A2',
    A3Production = 'A3',
    A4ToA5 = 'A4-A5',
    A4TransportToFinalDestination = 'A4',
    A5Installation= 'A5',
    B1toB7 = 'B1-B7',
    B1UsagePhase = 'B1',
    B2Maintenance = 'B2',
    B3Repair = 'B3',
    B4Replacement = 'B4',
    B5UpdateUpgradeRefurbishing = 'B5',
    B6UsageEnergy = 'B6',
    B7UsageWater = 'B7',
    C1toC4 = 'C1-C4',
    C1Reassembly = 'C1',
    C2toC4 = 'C2-C4',
    C2TransportToRecycler = 'C2',
    C3Recycling = 'C3',
    C4Landfill = 'C4',
    DReuse = 'D',
}
